"""
Pragma Code Generator — C target
Walks the AST and emits C99 source code.

Methods:
  generate(program: Program, safe: bool = False) -> str

  safe=True  emits runtime bounds checks on every array subscript via
  pragma_safe_index().  Requires GCC (uses __extension__ statement exprs).
"""

from typing import List, Any, Optional
from ast_nodes import *


# ── Type map ───────────────────────────────────────────────────────────────────

_TYPE_MAP = {
    'int':        'int',       'integer':    'int',
    'int8':       'int8_t',    'integer8':   'int8_t',
    'int16':      'int16_t',   'integer16':  'int16_t',
    'int32':      'int32_t',   'integer32':  'int32_t',
    'int64':      'int64_t',   'integer64':  'int64_t',
    'uint8':      'uint8_t',
    'uint16':     'uint16_t',
    'uint32':     'uint32_t',
    'uint64':     'uint64_t',
    'double':     'double',
    'float':      'double',    # use double precision by default
    'String':     'char*',
    'bool':       'bool',
    'void':       'void',
}

def _ct(name: str) -> str:
    """Map a Pragma type name to its C equivalent."""
    return _TYPE_MAP.get(name, name)   # unknown → pass through (user-defined)

# Extra preamble injected when --safe is active
_SAFE_PREAMBLE = """\
#include <assert.h>

/* pragma_safe_index: bounds-checked array access (safe mode).
   Aborts with a clear message if index is out of range.
   Uses GCC __extension__ statement expression so the result is an lvalue. */
#define pragma_safe_index(arr, idx, len) __extension__({\
    int __idx = (int)(idx);\
    int __len = (int)(len);\
    if (__idx < 0 || __idx >= __len) {\
        fprintf(stderr, "Pragma bounds error: index %d out of range [0, %d)\\n", __idx, __len);\
        exit(1);\
    }\
    (arr)[__idx];\
})
"""

# Standard preamble emitted at top of every generated file
_PREAMBLE = """\
/* Generated by Pragma — do not edit */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

/* pragma_print: type-generic print via C11 _Generic */
#define pragma_print(x) _Generic((x),  \\
    int:      printf("%d\\n",   (int)(x)),            \\
    long:     printf("%ld\\n",  (long)(x)),            \\
    int8_t:   printf("%d\\n",   (int)(x)),             \\
    int16_t:  printf("%d\\n",   (int)(x)),             \\
    int32_t:  printf("%d\\n",   (int32_t)(x)),         \\
    int64_t:  printf("%lld\\n", (long long)(x)),       \\
    uint8_t:  printf("%u\\n",   (unsigned)(x)),        \\
    uint16_t: printf("%u\\n",   (unsigned)(x)),        \\
    uint32_t: printf("%u\\n",   (uint32_t)(x)),        \\
    uint64_t: printf("%llu\\n", (unsigned long long)(x)), \\
    double:   printf("%g\\n",   (double)(x)),          \\
    bool:     printf("%s\\n",   (x) ? "true" : "false"), \\
    char*:    printf("%s\\n",   (char*)(x)),           \\
    default:  printf("<object>\\n")                    \\
)
"""


# ── Code generator ─────────────────────────────────────────────────────────────

class CodeGen:
    """
    Walks the Pragma AST and produces C source.
    Inputs:  program: Program, safe: bool
    Outputs: str  — C source text
    """

    def __init__(self, safe: bool = False):
        self._lines: List[str] = []
        self._depth = 0
        self._safe = safe
        self._current_object: Optional[str] = None   # name of object being generated
        self._current_parent: Optional[str] = None   # parent type of current object

    # ── Output helpers ────────────────────────────────────────────────────────

    def _emit(self, text: str = ''):
        self._lines.append('    ' * self._depth + text)

    def _emit0(self, text: str = ''):
        """Emit at depth 0 regardless of current indentation."""
        self._lines.append(text)

    def _push(self): self._depth += 1
    def _pop(self):  self._depth -= 1
    def _blank(self): self._lines.append('')

    def result(self) -> str:
        return '\n'.join(self._lines).rstrip() + '\n'

    # ── Entry point ───────────────────────────────────────────────────────────

    def generate(self, prog: Program) -> str:
        self._emit0(_PREAMBLE)
        if self._safe:
            self._emit0(_SAFE_PREAMBLE)

        # GLOBAL blocks: forward decls + type defs + functions + global vars
        for gb in prog.globals:
            self._block_body(gb.body)
            self._blank()

        # MAIN blocks: wrapped in int main(void)
        if prog.mains:
            self._emit0('int main(void) {')
            self._push()
            for mb in prog.mains:
                self._block_body(mb.body)
            self._emit0('    return 0;')
            self._pop()
            self._emit0('}')

        return self.result()

    def _block_body(self, stmts: List[Any]):
        for s in stmts:
            self._stmt(s)

    # ── Statement dispatch ────────────────────────────────────────────────────

    def _stmt(self, node: Any):
        t = type(node)
        dispatch = {
            ImportDecl:    self._s_import,
            VarDecl:       self._s_var,
            ConstantDecl:  self._s_constant,
            ArrayDecl:     self._s_array,
            ListDecl:      self._s_list,
            FunctionDecl:  self._s_func,
            ObjectDecl:    self._s_object,
            InterfaceDecl: self._s_interface,
            MandateDecl:   self._s_mandate,
            AssignStmt:    self._s_assign,
            ReturnStmt:    self._s_return,
            PrintStmt:     self._s_print,
            IfStmt:        self._s_if,
            ForStmt:       self._s_for,
            ForEachStmt:   self._s_foreach,
            WhileStmt:     self._s_while,
            TryStmt:       self._s_try,
            ConditionsStmt:self._s_conditions,
            EscapeStmt:    lambda n: self._emit('break;'),
            SkipStmt:      lambda n: self._emit('continue;'),
            NewStmt:       self._s_new_stmt,
            RawBlock:      self._s_raw,
            PointerDecl:   self._s_pointer,
            MemAccess:     lambda n: self._emit(self._e(n) + ';'),
            DerefExpr:     lambda n: self._emit(self._e(n) + ';'),
            PostfixOp:     self._s_postfix,
            CallExpr:      lambda n: self._emit(self._e(n) + ';'),
            Identifier:    lambda n: self._emit(self._e(n) + ';'),
            CastExpr:      lambda n: self._emit(self._e(n) + ';'),
            IndexExpr:     lambda n: self._emit(self._e(n) + ';'),
        }
        handler = dispatch.get(t)
        if handler:
            handler(node)
        else:
            self._emit(f'/* [unhandled: {t.__name__}] */')

    # ── Statement emitters ────────────────────────────────────────────────────

    def _s_import(self, node: ImportDecl):
        self._emit0(f'#include "{node.module}.h"')

    def _s_var(self, node: VarDecl):
        ct = _ct(node.type_name)
        if node.init is not None:
            self._emit(f'{ct} {node.name} = {self._e(node.init)};')
        else:
            self._emit(f'{ct} {node.name};')

    def _s_constant(self, node: ConstantDecl):
        ct = _ct(node.type_name)
        self._emit(f'const {ct} {node.name} = {self._e(node.init)};')

    def _s_array(self, node: ArrayDecl):
        """array[Type] name = [a, b, c]"""
        ct = _ct(node.elem_type)
        if node.init:
            n = len(node.init)
            items = ', '.join(self._e(x) for x in node.init)
            self._emit(f'{ct} {node.name}[{n}] = {{{items}}};')
            self._emit(f'int {node.name}_len = {n};')
        else:
            self._emit(f'{ct}* {node.name} = NULL;  /* dynamic array — set size at runtime */')
            self._emit(f'int {node.name}_len = 0;')

    def _s_list(self, node: ListDecl):
        """List[Type] name = [a, b, c]  — emitted as fixed array + count"""
        ct = _ct(node.elem_type)
        if node.init:
            items = ', '.join(self._e(x) for x in node.init)
            n = len(node.init)
            self._emit(f'{ct} {node.name}[{n}] = {{{items}}};')
            self._emit(f'int {node.name}_len = {n};')
        else:
            self._emit(f'{ct}* {node.name} = NULL;')
            self._emit(f'int {node.name}_len = 0;')

    def _s_func(self, node: FunctionDecl, self_type: str = '', parent_type: str = ''):
        """Emit a C function definition."""
        ct_ret = _ct(node.return_type) if node.return_type != 'void' else 'void'
        params = []
        if self_type:
            params.append(f'{self_type}* self')
        for p in node.params:
            params.append(f'{_ct(p.type_name)} {p.name}')
        param_str = ', '.join(params) if params else 'void'

        prefix = f'{self_type}_' if self_type else ''
        self._emit0(f'{ct_ret} {prefix}{node.name}({param_str}) {{')
        self._push()
        old_obj = self._current_object
        old_par = self._current_parent
        self._current_object = self_type or None
        self._current_parent = parent_type or None
        if node.body:
            self._block_body(node.body)
        else:
            self._emit('/* interface method — implement in subtype */')
        self._current_object = old_obj
        self._current_parent = old_par
        self._pop()
        self._emit0('}')
        self._blank()

    def _s_object(self, node: ObjectDecl):
        # 1. Struct typedef
        self._emit0(f'typedef struct {node.name} {{')
        self._push()
        if node.parent:
            self._emit(f'{node.parent} base;  /* inherits {node.parent} */')
        if node.fields:
            for f in node.fields:
                self._emit(f'{_ct(f.type_name)} {f.name};')
        else:
            self._emit('char _placeholder;')
        self._pop()
        self._emit0(f'}} {node.name};')
        self._blank()

        # 2. Constructor:  TypeName newTypeName(fields...)
        #    Includes parent fields first if inheriting
        all_fields = node.fields   # just own fields; user passes parent separately
        if all_fields:
            cparams = ', '.join(f'{_ct(f.type_name)} {f.name}' for f in all_fields)
            self._emit0(f'{node.name} new{node.name}({cparams}) {{')
            self._push()
            self._emit(f'{node.name} __obj;')
            for f in all_fields:
                self._emit(f'__obj.{f.name} = {f.name};')
            self._emit(f'return __obj;')
            self._pop()
            self._emit0('}')
            self._blank()

        # 3. Interface vtable instances
        for iface in node.ifaces:
            self._s_object_vtable(node, iface)

        # 4. Methods
        for method in node.methods:
            self._s_func(method, self_type=node.name, parent_type=node.parent or '')

    def _s_object_vtable(self, node: ObjectDecl, iface: str):
        """Generate a static vtable for one interface the object implements."""
        # We emit a forward reference; the actual vtable is filled after methods are defined
        self._emit0(f'/* {node.name} implements {iface} — vtable filled after method defs */')

    def _s_interface(self, node: InterfaceDecl):
        """interface Athlete → C struct of function pointers."""
        self._emit0(f'typedef struct {node.name} {{')
        self._push()
        for m in node.methods:
            ct_ret = _ct(m.return_type) if m.return_type != 'void' else 'void'
            param_types = ', '.join(
                ['void*'] + [_ct(p.type_name) for p in m.params]
            )
            self._emit(f'{ct_ret} (*{m.name})({param_types});')
        self._pop()
        self._emit0(f'}} {node.name};')
        self._blank()

    def _s_mandate(self, node: MandateDecl):
        """mandate Priority low=1, medium=2 ... → C enum"""
        self._emit0(f'typedef enum {{')
        self._push()
        auto_val = 0
        for i, m in enumerate(node.members):
            val = m.value if m.value is not None else auto_val
            auto_val = val + 1
            comma = ',' if i < len(node.members) - 1 else ''
            self._emit(f'{node.name}_{m.name} = {val}{comma}')
        self._pop()
        self._emit0(f'}} {node.name};')
        self._blank()

    def _s_assign(self, node: AssignStmt):
        self._emit(f'{self._e(node.target)} {node.op} {self._e(node.value)};')

    def _s_return(self, node: ReturnStmt):
        if node.value is not None:
            self._emit(f'return {self._e(node.value)};')
        else:
            self._emit('return;')

    def _s_print(self, node: PrintStmt):
        self._emit(f'pragma_print({self._e(node.value)});')

    def _s_if(self, node: IfStmt):
        self._emit(f'if ({self._e(node.condition)}) {{')
        self._push()
        self._block_body(node.body) if node.body else self._emit('/* empty */')
        self._pop()
        self._emit('}')
        for ec in node.elif_clauses:
            self._emit(f'else if ({self._e(ec.condition)}) {{')
            self._push()
            self._block_body(ec.body) if ec.body else self._emit('/* empty */')
            self._pop()
            self._emit('}')
        if node.else_body is not None:
            self._emit('else {')
            self._push()
            self._block_body(node.else_body) if node.else_body else self._emit('/* empty */')
            self._pop()
            self._emit('}')

    def _s_for(self, node: ForStmt):
        """for int i = 0 while i < 10 do i++  →  C for loop"""
        init = node.init
        ct = _ct(init.type_name)
        start = self._e(init.init) if init.init else '0'
        cond = self._e(node.condition)
        step = self._step_c(node.step, init.name)
        self._emit(f'for ({ct} {init.name} = {start}; {cond}; {step}) {{')
        self._push()
        self._block_body(node.body) if node.body else self._emit('/* empty */')
        self._pop()
        self._emit('}')

    def _step_c(self, step: Any, loop_var: str) -> str:
        """Convert a step expression to C for-loop increment string."""
        if isinstance(step, PostfixOp):
            return f'{self._e(step.operand)}++' if step.op == '++' else f'{self._e(step.operand)}--'
        if isinstance(step, AssignStmt):
            return f'{self._e(step.target)} {step.op} {self._e(step.value)}'
        return self._e(step)

    def _s_foreach(self, node: ForEachStmt):
        """for each item in arr  →  manual C index loop (no range-for in C99)"""
        arr = self._e(node.iterable)
        # Heuristic: if iterable ends with known list, use _len counter
        len_expr = f'{arr}_len'
        self._emit(f'for (int __i = 0; __i < {len_expr}; __i++) {{')
        self._push()
        self._emit(f'__auto_type {node.var} = {arr}[__i];')
        self._block_body(node.body) if node.body else self._emit('/* empty */')
        self._pop()
        self._emit('}')

    def _s_while(self, node: WhileStmt):
        self._emit(f'while ({self._e(node.condition)}) {{')
        self._push()
        self._block_body(node.body) if node.body else self._emit('/* empty */')
        self._pop()
        self._emit('}')

    def _s_try(self, node: TryStmt):
        # C has no native exceptions; emit a setjmp/longjmp skeleton with a comment
        self._emit('/* try block — C has no native exceptions; adapt to your error strategy */')
        self._emit('{')
        self._push()
        self._block_body(node.body)
        self._pop()
        self._emit('}')
        for catch in node.catches:
            exc = ', '.join(catch.exceptions)
            self._emit(f'/* catch ({exc} {catch.var}) */')
            self._emit(f'/* if (current_exception_is({exc!r})) {{ */')
            self._emit('{')
            self._push()
            self._block_body(catch.body)
            self._pop()
            self._emit('}')

    def _s_conditions(self, node: ConditionsStmt):
        """conditions x ... end conditions"""
        all_int = all(
            isinstance(c.value, IntLit) or c.is_default
            for c in node.cases
        )
        if all_int:
            self._emit(f'switch ({self._e(node.expr)}) {{')
            self._push()
            for case in node.cases:
                if case.is_default:
                    self._emit('default: {')
                else:
                    self._emit(f'case {self._e(case.value)}: {{')
                self._push()
                self._block_body(case.body)
                # Auto-break unless last statement is already escape/skip
                if not case.body or not isinstance(case.body[-1], (EscapeStmt, SkipStmt)):
                    self._emit('break;')
                self._pop()
                self._emit('}')
            self._pop()
            self._emit('}')
        else:
            # Non-integer cases: emit if/else chain
            for i, case in enumerate(node.cases):
                if case.is_default:
                    self._emit('else {')
                elif i == 0:
                    val = self._e(case.value)
                    expr = self._e(node.expr)
                    # String comparison needs strcmp
                    if isinstance(case.value, StringLit):
                        self._emit(f'if (strcmp({expr}, {val}) == 0) {{')
                    else:
                        self._emit(f'if ({expr} == {val}) {{')
                else:
                    val = self._e(case.value)
                    expr = self._e(node.expr)
                    if isinstance(case.value, StringLit):
                        self._emit(f'else if (strcmp({expr}, {val}) == 0) {{')
                    else:
                        self._emit(f'else if ({expr} == {val}) {{')
                self._push()
                self._block_body(case.body)
                self._pop()
                self._emit('}')

    def _s_new_stmt(self, node: NewStmt):
        self._emit(self._e_new(node) + ';')

    def _s_raw(self, node: RawBlock):
        self._emit('/* --- RAW block --- */')
        self._block_body(node.body)
        self._emit('/* --- end RAW --- */')

    def _s_pointer(self, node: PointerDecl):
        ct = _ct(node.type_name)
        target = node.target.target
        self._emit(f'{ct}* {node.name} = ({ct}*)(&{target});')

    def _s_postfix(self, node: PostfixOp):
        if node.op == '++':
            self._emit(f'{self._e(node.operand)}++;')
        else:
            self._emit(f'{self._e(node.operand)}--;')

    # ── Expression emitter ────────────────────────────────────────────────────

    def _e(self, node: Any) -> str:
        t = type(node)

        if t is Identifier:   return node.name
        if t is IntLit:       return str(node.value)
        if t is FloatLit:
            s = str(node.value)
            return s if '.' in s or 'e' in s else s + '.0'
        if t is StringLit:    return f'"{node.value}"'
        if t is BoolLit:      return 'true' if node.value else 'false'
        if t is NullLit:      return 'NULL'
        if t is EmptyLit:     return 'NULL'   # or "" for strings; context-dependent

        if t is SuperRef:
            parent = self._current_parent or '__parent__'
            return f'(({parent}*)self)'

        if t is FieldAccess:
            obj = self._e(node.obj)
            # super.Method → ParentType_Method call handled in CallExpr
            if isinstance(node.obj, SuperRef):
                parent = self._current_parent or '__parent__'
                return f'{parent}_{node.field}'
            # 'self' is always a pointer inside methods → use ->
            if isinstance(node.obj, Identifier) and node.obj.name == 'self':
                return f'self->{node.field}'
            return f'{obj}.{node.field}'

        if t is CallExpr:
            func = node.func
            # super.Method(args) → ParentType_Method((ParentType*)self, args)
            if isinstance(func, FieldAccess) and isinstance(func.obj, SuperRef):
                parent = self._current_parent or '__parent__'
                args = ', '.join([f'({parent}*)self'] + [self._e(a) for a in node.args])
                return f'{parent}_{func.field}({args})'
            # obj.method(args) → TypeName_method(obj, args)  if obj is known struct
            if isinstance(func, FieldAccess):
                obj_expr = self._e(func.obj)
                args = ', '.join([f'&{obj_expr}'] + [self._e(a) for a in node.args])
                return f'{func.field}({args})'
            fn = self._e(func)
            args = ', '.join(self._e(a) for a in node.args)
            return f'{fn}({args})'

        if t is BinOp:
            op = node.op
            # & and | stay as bitwise C operators — work correctly on bools (0/1)
            # and on ints for flag manipulation. No short-circuit, by design.
            if op == 'delta':  op = '^'
            elif op == 'left': op = '<<'
            elif op == 'right': op = '>>'
            return f'({self._e(node.left)} {op} {self._e(node.right)})'

        if t is UnaryOp:
            op = node.op
            if op == '!':    return f'(!{self._e(node.operand)})'
            if op == 'flip': return f'(~{self._e(node.operand)})'
            return f'({op}{self._e(node.operand)})'

        if t is PostfixOp:
            sym = '++' if node.op == '++' else '--'
            return f'{self._e(node.operand)}{sym}'

        if t is IndexExpr:
            arr = self._e(node.array)
            idx = self._e(node.index)
            if self._safe:
                len_expr = f'{arr}_len'
                return f'pragma_safe_index({arr}, {idx}, {len_expr})'
            return f'{arr}[{idx}]'

        if t is CastExpr:
            return f'(({_ct(node.target_type)})({self._e(node.expr)}))'

        if t is NewStmt:     return self._e_new(node)
        if t is SizeOf:      return f'sizeof({_ct(node.type_name)})'
        if t is MemAccess:   return f'(*((volatile uint8_t*)({self._e(node.address)})))'
        if t is DerefExpr:   return f'(*{self._e(node.pointer)})'
        if t is AddressOf:   return f'(&{node.target})'

        return f'/* [unhandled expr: {t.__name__}] */'

    def _e_new(self, node: NewStmt) -> str:
        """new TypeName[a, b]  →  newTypeName(a, b)"""
        if node.args:
            args = ', '.join(self._e(a) for a in node.args)
            return f'new{node.type_name}({args})'
        return f'({node.type_name}){{0}}'   # zero-initialised struct literal


# ── Public API ─────────────────────────────────────────────────────────────────

def generate(program: Program, safe: bool = False) -> str:
    """Walk the Program AST and return C source as a string."""
    return CodeGen(safe=safe).generate(program)
