/* Generated by Pragma — do not edit */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

/* pragma_print: type-generic print via C11 _Generic */
#define pragma_print(x) _Generic((x),  \
    int:      printf("%d\n",   (int)(x)),            \
    long:     printf("%ld\n",  (long)(x)),            \
    int8_t:   printf("%d\n",   (int)(x)),             \
    int16_t:  printf("%d\n",   (int)(x)),             \
    int32_t:  printf("%d\n",   (int32_t)(x)),         \
    int64_t:  printf("%lld\n", (long long)(x)),       \
    uint8_t:  printf("%u\n",   (unsigned)(x)),        \
    uint16_t: printf("%u\n",   (unsigned)(x)),        \
    uint32_t: printf("%u\n",   (uint32_t)(x)),        \
    uint64_t: printf("%llu\n", (unsigned long long)(x)), \
    double:   printf("%g\n",   (double)(x)),          \
    bool:     printf("%s\n",   (x) ? "true" : "false"), \
    char*:    printf("%s\n",   (char*)(x)),           \
    default:  printf("<object>\n")                    \
)

const int MAX_SPEED = 100;
typedef enum {
    Priority_low = 1,
    Priority_medium = 2,
    Priority_high = 3
} Priority;

typedef struct Athlete {
    void (*Train)(void*);
    int (*GetSpeed)(void*);
} Athlete;

typedef struct Runner {
    char* name;
    int age;
    double speed;
} Runner;

Runner newRunner(char* name, int age, double speed) {
    Runner __obj;
    __obj.name = name;
    __obj.age = age;
    __obj.speed = speed;
    return __obj;
}

typedef struct Cyclist {
    Runner base;  /* inherits Runner */
    int bikeType;
} Cyclist;

Cyclist newCyclist(int bikeType) {
    Cyclist __obj;
    __obj.bikeType = bikeType;
    return __obj;
}

/* Cyclist implements Athlete — vtable filled after method defs */
void Cyclist_Train(Cyclist* self) {
    pragma_print("Cyclist training");
}

int Cyclist_GetSpeed(Cyclist* self) {
    return ((int)(self->speed));
}

int Add(int a, int b) {
    return (a + b);
}

int Factorial(int n) {
    if ((n <= 1)) {
        return 1;
    }
    return (n * Factorial((n - 1)));
}


int main(void) {
    int x = 10;
    double pi = 3.14159;
    char* msg = "Pragma works";
    bool done = false;
    pragma_print(msg);
    pragma_print(Add(3, 7));
    pragma_print(Factorial(6));
    pragma_print(MAX_SPEED);
    x += 5;
    x *= 2;
    pragma_print(x);
    if ((x > 30)) {
        pragma_print("large");
    }
    else if ((x > 15)) {
        pragma_print("medium");
    }
    else {
        pragma_print("small");
    }
    int count = 0;
    while ((count < 3)) {
        count++;
        pragma_print(count);
    }
    for (int i = 0; (i < 4); i++) {
        pragma_print(i);
    }
    int scores[4] = {95, 87, 72, 100};
    char* names[3] = {"Alice", "Bob", "Carol"};
    int names_len = 3;
    for (int __i = 0; __i < names_len; __i++) {
        __auto_type name = names[__i];
        pragma_print(name);
    }
    int j = 0;
    while ((j < 10)) {
        j++;
        if ((j == 5)) {
            break;
        }
        if (((j % 2) == 0)) {
            continue;
        }
        pragma_print(j);
    }
    int code = 2;
    switch (code) {
        case 1: {
            pragma_print("one");
            break;
        }
        case 2: {
            pragma_print("two");
            break;
        }
        case 3: {
            pragma_print("three");
            pragma_print("still three");
            break;
        }
        default: {
            pragma_print("other");
            break;
        }
    }
    int p = Priority_high;
    pragma_print(p);
    int flags = 0;
    flags = (flags | 4);
    flags = (flags ^ 1);
    flags = (flags << 2);
    flags = (flags >> 1);
    flags = (~flags);
    pragma_print(flags);
    double f = 3.9;
    int truncated = ((int)(f));
    pragma_print(truncated);
    Runner r = newRunner("Jake", 24, 9.8);
    pragma_print(r.name);
    char* blank = NULL;
    int nothing = 0;
    return 0;
}
